server:
  servlet.context-path: /${spring.application.name}
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
management:
  server:
    port: 8181

  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    loggers:
      enabled: true
    threaddump:
      enabled: true
    info:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,threaddump

spring:
  threads:
    virtual:
      enabled: true
  mvc.problemdetails:
      enabled: true
  application:
    name: people-service
  datasource:
    url: ${SPRING_POSTGRES_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_POSTGRES_DATASOURCE_USERNAME:username}
    password: ${SPRING_POSTGRES_DATASOURCE_PASSWORD:password}

    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  ai:
    ollama:
      base-url: ${SPRING_AI_OLLAMA_BASE_URL:http://localhost:11436}
      chat:
        options:
          model: gemma3:270m
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      pgvector:
        schema-name: person
        table-name: person_note_embedding
        dimensions: 768
        remove-existing-vector-store-table: false
ai:
  search:
    top-k: 5
    similarity-threshold: 0.55

logging:
  level:
    org.springframework.ai.vectorstore.pgvector: DEBUG
    org.springframework.jdbc.core: DEBUG
    com.plavonra.person.PersonService: DEBUG
    org.springframework.web: DEBUG

springdoc:
  paths-to-exclude: /error
  swagger-ui:
    path: /swagger-ui.html
    query-config-enabled: false
    csrf:
      enabled: true